### ISSUE TITLE
what is this???? is this for the audio thing??

### ISSUE THREAD

**Issue by srcoggin** [samh06/gis#1]

**Comment by samh06** [comment]
no

[A Geographic Information System (GIS) is a computer system that analyzes and displays geographically referenced information.](https://www.usgs.gov/faqs/what-geographic-information-system-gis#:~:text=A%20Geographic%20Information%20System%20(GIS)%20is%20a%20computer%20system%20that,Where%20are%20USGS%20streamgages%20located%3F)
